/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClassListController;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Clase;
import model.Task;
import organizme.MainPanel;

/**
 *
 * @author josuearreola
 */
public class ClaseInfo extends javax.swing.JFrame {

    /**
     * Creates new form ClaseInfo
     */
    ClassListController clc = new ClassListController();
    public ClaseInfo(Clase clase) {
        initComponents();
        fillInputsFromClass(clase);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        claseNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        claseLink = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        claseMaestro = new javax.swing.JTextField();
        saveClase = new javax.swing.JButton();
        deleteClae1 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        claseID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre de la clase:");

        jLabel2.setText("Link");

        jLabel3.setText("Maestro");

        saveClase.setText("Guardar Cambios");
        saveClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveClaseActionPerformed(evt);
            }
        });

        deleteClae1.setText("Borrar Clase");
        deleteClae1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteClae1ActionPerformed(evt);
            }
        });

        backBtn.setText("Volver");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        claseID.setText("ID");

        jLabel5.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteClae1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveClase)
                        .addContainerGap(66, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(claseNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                    .addComponent(claseLink)
                                    .addComponent(claseMaestro))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(claseID)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(claseID)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(claseNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(claseLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(claseMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteClae1)
                    .addComponent(saveClase))
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveClaseActionPerformed
        boolean validation = validateFields();
        if(!validation){
            JOptionPane.showMessageDialog(null, "No dejes campos en blanco...");
            return;
        }
        Clase nc = new Clase(claseNombre.getText(), claseLink.getText(), claseMaestro.getText(),Integer.parseInt(claseID.getText()));
        boolean wasUpdated = clc.patchClassInfo(nc);
        if(wasUpdated){
            ClasesInfoFrame cif = new ClasesInfoFrame();
            cif.setVisible(true);
            dispose();
            
            JOptionPane.showMessageDialog(null, "Cambios guardados!");
            
        }else{
            JOptionPane.showMessageDialog(null, "Reduce el número de caracteres :/!");

        }
    }//GEN-LAST:event_saveClaseActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        ClasesInfoFrame cif = new ClasesInfoFrame();
        cif.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void deleteClae1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteClae1ActionPerformed
        boolean wasDeleted = clc.deleteClass(Integer.valueOf(claseID.getText()));
        if(wasDeleted){
            JOptionPane.showMessageDialog(null, "Clase eliminada!");
            backBtnActionPerformed(evt);
        }else{
            JOptionPane.showMessageDialog(null, "Algo salió mal :/!");

        }
    }//GEN-LAST:event_deleteClae1ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel claseID;
    private javax.swing.JTextField claseLink;
    private javax.swing.JTextField claseMaestro;
    private javax.swing.JTextField claseNombre;
    private javax.swing.JButton deleteClae1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton saveClase;
    // End of variables declaration//GEN-END:variables

    private void fillInputsFromClass(Clase clase) {
        claseNombre.setText(clase.getClassName());
        claseLink.setText(clase.getLinkUrl());
        claseMaestro.setText(clase.getTeacherName());
        claseID.setText(String.valueOf(clase.getId()));
    }

    private boolean validateFields() {
        return !(claseNombre.getText().isEmpty() || claseLink.getText().isEmpty() || claseLink.getText().isEmpty());
    }
}
